# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 15 0-11/3 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: SignIn
      run: |
        python ./wechatdailysend.py
      #env:
        #STUID: ${{ secrets.STUID }}
        #PW: ${{ secrets.PW }}
        #SERVER: ${{ secrets.SERVER }}
        #SCKEY: ${{ secrets.SCKEY }}
        #MAIL_NOTICE: ${{ secrets.MAI_NOTICE }}
        #MAILBOX: ${{ secrets.MAILBOX }}
