# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Send

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 9 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: runpy
      run: |
      
        python ./wechatdailysend.py
        
      env:
        APPID: ${{ secrets.APPID }}
        APPSECRET: ${{ secrets.APPSECRET }}
        TEMPLATEID: ${{ secrets.TEMPLATEID }}
        OPENID: ${{ secrets.OPENID }}
        CITY: ${{ secrets.CITY }}
        NAME: ${{ secrets.NAME }}
        ANNORDAY: ${{ secrets.ANNORDAY }}
        BIRTHDAT: ${{ secrets.BIRTHDAT }}

